### ISSUE TITLE
pull request with updates

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/Census-Data-in-R#13]
* Changed package management in setup
 * Restructured challenges and solutions as separate .Rmd files to fit conventions of newly developed R material, like [R-Data-Visualization](https://github.com/dlab-berkeley/R-Data-Visualization)
 * Added small narrative tweaks, allows for knitting on all workshop material.
 * Added leaflet example
 * Added DataHub functionality, link in readme: (note the link goes to my branch, and needs to be updated if merged), can test link here if you like:
[DataHub LInk](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FAverysaurus%2FCensus-Data-in-R-1&urlpath=rstudio%2F&branch=master)

**Comment by Averysaurus** [comment]
@ifarah changed some stuff for us. :)

**Comment by pattyf** [comment]
This has been merged.
