### ISSUE TITLE
Challenge solution throws error

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/Census-Data-in-R#2]
When running line 525 from Census_data_maps-slides.Rmd: 

```
# Fetch the 2000 pop data
pop2000 <- get_decennial(geography = "state", variables = "P001001", year = 2000)
```
I get an error: 
```
Getting data from the 2000 decennial Census
Error : Your API call has errors.  The API message returned is <html><head><title>Error report</title></head><body><h1>HTTP Status 404 - /data/2000/sf3</h1></body></html>.
Error in UseMethod("gather") : 
  no applicable method for 'gather' applied to an object of class "character"
```
Looked up the function and toggled with arguments, have not been able make it run. Not sure exactly what's wrong yet, other `get_decennial()` calls work fine, no problem.

**Comment by Averysaurus** [comment]
Error is still present in last workshop session 2022-03-16. Best solution I found is [here](https://github.com/walkerke/tidycensus/issues/403). Since installing packages from git is a little much I'm going to restructure the challenge and make a fork available to merge.

**Comment by Averysaurus** [comment]
issue still present at 2022-03-16 workshop. Looking for workaround, having trouble accessing 2000 census data via `get_decennial`.  may need to restructure challenge question.

**Comment by pattyf** [comment]
Hi Avery, I've never had that problem in all the times I've run this workshop. I'll take a look at it since I'm teaching this workshop on April 1. thanks!

**Comment by Averysaurus** [comment]
@pattyf the error occured because we both had an older, un-updated `tidycensus` package installed. I updated package versions locally and the calls work here, no problem.
